[gspread]
type = "service_account"
project_id = "dulcet-radar-456907-u4"
private_key_id = "e9a69229c8ebbaafb5f1d1b188f1bc89e228640c"
private_key = "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADAN...\\n-----END PRIVATE KEY-----\\n"
client_email = "try-844@dulcet-radar-456907-u4.iam.gserviceaccount.com"
client_id = "108881545805856843745"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/try-844%40dulcet-radar-456907-u4.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
{
  "type": "service_account",
  "project_id": "dulcet-radar-456907-u4",
  "private_key_id": "e9a69229c8ebbaafb5f1d1b188f1bc89e228640c",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDk/SxXAB5KgZHa\n3q48vJQ8ii7H2ukertGvp/KMeUmwiFCh9FAFRt18ky0zLWhL94sY10sqf1vmuVBo\nWHaeD9VroWoiSA22W6Ep4DUBmq/4pw5vbjcZX06RO8SraAh77bt1zXhRC1CiKQ74\nACKau9qH6ZXddXEM+jqFSgVb2enN1ZGWkG3Jpj+KeAHbdgP/f47o6BgSlDApCfam\nzOSWHTj8m4nZnwhy77iDBm+22M2Hz2GEkXimlxQ6z6eVevt9s4z9K3+hnIaw5ENq\nG1tfdkSddM+pWU9zexfvIMMuhLbgAGdUOnEPkOYxYx+f/YcG27661HjAbwprhUqf\nt1fJpHDdAgMBAAECggEARuh3AIHS33N7/PCTt88VgCGyFsUdBxlPaTtyijlMrlOn\n1F7ZIKkvENJqXryi3VNMSWbxqblCdhHQal9qa8uvZOLZAMCbLmr1XwhEobiK4U6p\n06uneD3hEGwXnJRcfDPDptj3dvEwCOb58aXpEU02gHu+opMpbMFXucqQGj9CfTAd\nJZBmslHxyx6jslEXlDD1cIkLsh+km60dN+CwBVhnSbkBLsAT/XLjGn8qwWFNqDmn\nH88tPwSWIhDgYJHIVpzrHtzhbeA8bAXQtEFpBsrZdC1RqiMzVTyZ20EOjW/ZoxCg\nZg6gar/Tlez538b5LPu2WHDKjk4hyfST1QWGDX3G6QKBgQD32uUuBLPQQzLKKLh1\nEGRMxeJ4+Rns6d5Z8T5/BhgDS3XLohmu4L7TRCfYIzUaIeeBLFPlmOjJpssmqhfe\nzbhQQ0nrjBDPoeRv0WmQ4IFdQvr4qY6nN6+2qUwvRtekFEc1Qhl1GOmcJWhP2AxR\n4I6pgfrOsbZ+lo9jM8S7pnvyrwKBgQDsg5CngJ5RvzRHTY/LRBJIC/tMwxn0L+96\n1tWrmSXfm8zGEPRzG+FqsLMupFCvEIoBx7Lzx4vDauGhn5jJx44GDq0fl3riLAKE\nU10HuXbuevYYZmM5cmqWVNr9B07uE2vZjvMcl7aS6WItjFcfDKg4D8NMeATDIg5h\nAYOdCGRoMwKBgGOQBLvlm62vMLnQfbhYq1HDs+PQfL+UeoM6y1YPRpocN+di6Fo9\nYapQGIlUK0KiF/LlsZXrRKesXrLbZNdVYBKt1QXPr/kYGUFpp7RQ2uZxv4sf4XP+\nhJEllLrxBDKfCrO0J7HIHh9hT3OzX8+MGwKweeWJsbtME7FP3Flc2TF1AoGAdZkt\nMbwH/El/6vwrxTvBg0VB3HcdzoaPIprzfvEVHcvP06PWh+2S9YOKdGSLIaCtnhj3\nZ7MOUUoxijVauOmaOnTNq+mb1h1f2v/AP/j9o7JL7vHp4ER9ruXeRPV/T20ksPYc\n91iQFRgqEs+2+d9HPSjJSJpcc9HZKG6iTFBB7HUCgYEA0gVPaaaDprCHcMUPvqGu\nm19v0UAkvS3x43S/2aJCLiR4SbamYMf9ynI6tEgGNQphpV8BvZUJC+NwP1bGYgb2\nn39+zDlipmo3xUZhRF8WVxFheelEsI8jd7L1jlsYiAr3I5fm7wa27L9aMQqMUH+7\nXEzXccGGhlgy9nfZ/geLNRk=\n-----END PRIVATE KEY-----\n",
  "client_email": "try-844@dulcet-radar-456907-u4.iam.gserviceaccount.com",
  "client_id": "108881545805856843745",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/try-844%40dulcet-radar-456907-u4.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
